dev:
	@echo "Starting the development enviroment..."
	docker compose -f dev.compose.yml up -d

dev_build:
	docker compose -f dev.compose.yml build

dev_stop:
	docker compose -f dev.compose.yml down

build:
	@echo "Building the project..."

test:
	@echo "Testing the project..."

run:
	@echo "Running the project..."

build_and_run:
	@echo "Building and running the project..."

swarm:
	@echo "creating local images"
	@echo "Swarming the project..."

stop:
	@echo "Stopping the project..."
